name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Connexion à GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construire l'image Docker
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/churnguard:${{ github.ref_name }} \
            -t ghcr.io/${{ github.repository_owner }}/churnguard:latest \
            .

      - name: Publier l'image Docker
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/churnguard:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/churnguard:latest